.col100.heritages
					+hidden-input('outlook_traits_chosen').heritage_traits_chosen(value='0')
					.content
						+hidden-input('show_outlook_doomsayer').hider(value='1')
						.heritage
							.label(data-i18n='doomsayer_traits').text.title
							ul
									
								li
									+checkbox('trait_debater').checkbox.diamondbox.small(value='0')
									span.label(data-i18n='trait_debater').smallcaps 
									span.label(data-i18n='colon')
									span.label(data-i18n='trait_debater_description')
									+hidden-input('trait_debater').hider(value='0')
								li
									+checkbox('trait_dreamer').checkbox.diamondbox.small(value='0')
									span.label(data-i18n='trait_dreamer').smallcaps 
									span.label(data-i18n='colon')
									span.label(data-i18n='trait_dreamer_description')
									+hidden-input('trait_dreamer').hider(value='0')
								li
									+checkbox('trait_searcher').checkbox.diamondbox.small(value='0')
									span.label(data-i18n='trait_searcher').smallcaps 
									span.label(data-i18n='colon')
									span.label(data-i18n='trait_searcher_description')
									+hidden-input('trait_searcher').hider(value='0')
								li
									+checkbox('trait_skeptic').checkbox.diamondbox.small(value='0')
									span.label(data-i18n='trait_skeptic').smallcaps 
									span.label(data-i18n='colon')
									span.label(data-i18n='trait_skeptic_description')
									+hidden-input('trait_skeptic').hider(value='0')
						+hidden-input('show_outlook_herite').hider(value='1')
						.heritage
							.label(data-i18n='herite_traits').text.title
							ul
								li
									+checkbox('trait_anarchic').checkbox.diamondbox.small(value='0')
									span.label(data-i18n='trait_anarchic').smallcaps
									span.label(data-i18n='colon')
									span.label(data-i18n='trait_anarchic_description')
									+hidden-input('trait_anarchic').hider(value='0')
								li
									+checkbox('trait_free_thinker').checkbox.diamondbox.small(value='0')
									span.label(data-i18n='trait_free_thinker').smallcaps
									span.label(data-i18n='colon')
									span.label(data-i18n='trait_free_thinker_description')
									+hidden-input('trait_free_thinker').hider(value='0')
								li
									+checkbox('trait_subversive').checkbox.diamondbox.small(value='0')
									span.label(data-i18n='trait_subversive').smallcaps 
									span.label(data-i18n='colon')
									span.label(data-i18n='trait_subversive_description')
									+hidden-input('trait_subversive').hider(value='0')
								li
									+checkbox('trait_suspicious').checkbox.diamondbox.small(value='0')
									span.label(data-i18n='trait_suspicious').smallcaps 
									span.label(data-i18n='colon')
									span.label(data-i18n='trait_suspicious_description')
									+hidden-input('trait_suspicious').hider(value='0')
						+hidden-input('show_outlook_jacker').hider(value='1')
						.heritage
							.label(data-i18n='jacker_traits').text.title
							ul
								li
									+checkbox('trait_driven').checkbox.diamondbox.small(value='0')
									span.label(data-i18n='trait_driven').smallcaps 
									span.label(data-i18n='colon')
									span.label(data-i18n='trait_driven_description')
									+hidden-input('trait_driven').hider(value='0')
								li
									+checkbox('trait_protective').checkbox.diamondbox.small(value='0')
									span.label(data-i18n='trait_protective').smallcaps 
									span.label(data-i18n='colon')
									span.label(data-i18n='trait_protective_description')
									+hidden-input('trait_protective').hider(value='0')
								li
									+checkbox('trait_vengeful').checkbox.diamondbox.small(value='0')
									span.label(data-i18n='trait_vengeful').smallcaps 
									span.label(data-i18n='colon')
									span.label(data-i18n='trait_vengeful_description')
									+hidden-input('trait_vengeful').hider(value='0')
								li
									+checkbox('trait_warrior').checkbox.diamondbox.small(value='0')
									span.label(data-i18n='trait_warrior').smallcaps 
									span.label(data-i18n='colon')
									span.label(data-i18n='trait_warrior_description')
									+hidden-input('trait_warrior').hider(value='0')
						
						+hidden-input('show_outlook_lightbringer').hider(value='1')
						.heritage
							.label(data-i18n='lightbringer_traits').text.title
							ul
									
								li
									+checkbox('trait_connected').checkbox.diamondbox.small(value='0')
									span.label(data-i18n='trait_connected').smallcaps 
									span.label(data-i18n='colon')
									span.label(data-i18n='trait_connected_description')
									+hidden-input('trait_connected').hider(value='0')
								li
									+checkbox('trait_manipulator').checkbox.diamondbox.small(value='0')
									span.label(data-i18n='trait_manipulator').smallcaps 
									span.label(data-i18n='colon')
									span.label(data-i18n='trait_manipulator_description')
									+hidden-input('trait_manipulator').hider(value='0')
								li
									+checkbox('trait_motivator').checkbox.diamondbox.small(value='0')
									span.label(data-i18n='trait_motivator').smallcaps 
									span.label(data-i18n='colon')
									span.label(data-i18n='trait_motivator_description')
									+hidden-input('trait_motivator').hider(value='0')
								li
									+checkbox('trait_political').checkbox.diamondbox.small(value='0')
									span.label(data-i18n='trait_political').smallcaps 
									span.label(data-i18n='colon')
									span.label(data-i18n='trait_political_description')
									+hidden-input('trait_political').hider(value='0')